Add testing update for github actions on push to testing

diff --git a/.github/workflows/opw-testing.yml b/.github/workflows/opw-testing.yml
--- a/.github/workflows/opw-testing.yml
+++ b/.github/workflows/opw-testing.yml
@@ -50,7 +50,7 @@ jobs:
           count=0
           max_attempts=100
           while true; do
-            status_code=$(curl --write-out "%{http_code}\n" -v --output /dev/null ${{ vars.TESTING_SERVER }}:8069/web/login || echo "Curl failed")
+            status_code=$(curl --http1.0 --write-out "%{http_code}\n" -v --output /dev/null ${{ vars.TESTING_SERVER }}:8069/web/login || echo "Curl failed")
             if [ "$status_code" = "200" ]; then
               break
             else
