Add testing update for github actions on push to testing

diff --git a/.github/workflows/opw-testing.yml b/.github/workflows/opw-testing.yml
--- a/.github/workflows/opw-testing.yml
+++ b/.github/workflows/opw-testing.yml
@@ -44,32 +44,21 @@ jobs:
         run: |
           ssh ${{ vars.TESTING_USER }}@${{ vars.TESTING_SERVER }} 'cd /opt/odoo/odoo-addons/product_connect; sudo -u odoo git pull; sudo systemctl restart odoo'
         shell: bash
-      - name: Wait for website to be up (Python)
-        env:
-          PYTHONUNBUFFERED: 1
+      - name: Check if website is up
         run: |
-          python - <<'EOF'
-          import time, sys
-          import requests
-      
-          url = f"http://${{ vars.TESTING_SERVER }}:8069/web/login"
-          print("URL:", url, flush=True)
-          max_attempts = 100
-          attempt = 0
-      
-          while attempt < max_attempts:
-              try:
-                  response = requests.get(url, timeout=10)
-                  if response.status_code == 200:
-                      print("Received 200 OK")
-                      sys.exit(0)
-                  else:
-                      print(f"Attempt {attempt+1} failed: {e}", flush=True)
-              except Exception as e:
-                  print(f"Attempt {attempt+1} failed: {e}")
-              attempt += 1
-              time.sleep(5)
-          print(f"Failed to get 200 OK after {max_attempts} attempts")
-          sys.exit(1)
-          EOF
+          sleep 5
+          count=0
+          max_attempts=100
+          while true; do
+            status_code=$(ssh ${{ vars.TESTING_USER }}@${{ vars.TESTING_SERVER }} "curl --write-out '%{http_code}\n' --output /dev/null localhost:8069/web/login || echo 'Curl failed'")
+            if [ "$status_code" = "200" ]; then
+              break
+            else
+              count=$((count+1))
+              if [ $count -ge $max_attempts ]; then
+                exit 1
+              fi
+              sleep 5
+            fi
+          done
         shell: bash
